language: go

go:
  - 1.7
  - 1.8
  - 1.9

install:
  - make deps
  - go get github.com/mattn/goveralls

script:
  - make test

after_success:
  - goveralls -service=travis-ci -coverprofile .coverage/combined.txt
  - make list-external-deps > dependency_tree.txt && cat dependency_tree.txt
